# Generated by Django 3.2.4 on 2021-06-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(default='new job', max_length=32),
        ),
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.CharField(choices=[('not-run', 'not-run'), ('running', 'running'), ('done', 'done')], default='not-run', max_length=16),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('ok', 'ok'), ('error', 'error'), ('none', 'none')], default='none', max_length=16),
        ),
    ]
