# Generated by Django 3.2.4 on 2021-06-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmanager', '0004_jobrun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='run_count',
        ),
        migrations.RemoveField(
            model_name='job',
            name='state',
        ),
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
        migrations.AddField(
            model_name='jobrun',
            name='state',
            field=models.CharField(choices=[('not-run', 'not-run'), ('running', 'running'), ('done', 'done')], default='not-run', max_length=16),
        ),
        migrations.AddField(
            model_name='jobrun',
            name='status',
            field=models.CharField(choices=[('none', 'none'), ('ok', 'ok'), ('error', 'error')], default='none', max_length=16),
        ),
    ]
