# Generated by Django 3.2.4 on 2021-06-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmanager', '0005_auto_20210627_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='times_to_run',
            field=models.IntegerField(default=1),
        ),
    ]
