# Generated by Django 3.2.4 on 2021-06-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmanager', '0006_job_times_to_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrun',
            name='job_message',
            field=models.TextField(default=''),
        ),
    ]
